#####################################################
#               ROF_PlayerVault                     #
#               by RageOfFire                       #
#####################################################

# vault name
vault-title: 'ROF Vault'
# Let vault pickup item when player inventory is full ! REQUIRED: restart server !!!
vault-pickup:
  # Enable this feature
  enable: false
  # Time in second, each time plugin check for item around player
  interval: 3
  # Radius for plugin check for item around player
  radius: 3

# List item not allow to place in vault
# All available items: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
# Example:
# blacklist-items:
# - shulker_box
# - ...
# To blacklist Shulker Box and other item to vault
blacklist-items: []

#####################################################
#               Message                             #
#####################################################
messages:
  prefix: "&f[&6ROF_PlayerVault&f]"
  only-player: "&cOnly player can execute this command"
  command-reload: '&aSuccessfully reloaded ROF_PlayerVault plugin!'
  command-delete: '&aSuccessfully delete %player% vault %number% !'
  no-permission: '&cYour don''t have permission to do that.'
  usage-main: '&cUsage: /rofvault <command>'