name: ROF_PlayerVault
version: '${project.version}'
main: me.rof_playervault.ROF_PlayerVault
api-version: '1.13'
commands:
  rofvault:
    description: Main command for ROFPlayerVault
    usage: /rofvault <command>
    aliases:
    - vault
    - pv
permission:
  rofvault.admin:
    description: Permission for admin user plugin
    default: op
    children:
      rofvault.admin.reload: true
      rofvault.admin.delete: true
      rofvault.admin.view: true
      rofvault.admin.edit: true
      rofvault.use: true
  rofvault.use:
    description: Permission for open vault
    default: false